### ISSUE TITLE
Mod Download / 模组下载一览

### ISSUE THREAD

**Issue by Doreamonsky** [Doreamonsky/Panzer-War-Lit-Mod#59]
# Mod Download / 模组下载一览

Community 01/社区模组-1 : [Click To View/点击查看](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/ReadMe.md)

Community 02/社区模组-2 : [Click To View/点击查看](https://github.com/Doreamonsky/ModPackV2/blob/master/ReadMe.md)

国内百度网盘分流: https://pan.baidu.com/s/1mOxbxZtdv0l3qUjHr2QVxw

---

国内可能受网络影响，无法正常下载。可选择前往 <https://hub.waroftanks.cn/docs/#/> 进行安装

**Comment by Doreamonsky** [comment]
Click this to subscribe the update.

![TIM截图20191215185207](https://user-images.githubusercontent.com/12712112/70861648-017b2c80-1f6c-11ea-8969-29f944de0b81.png)

**Comment by Doreamonsky** [comment]
You can not reply$\color{#FF3030}{red}$

**Comment by Doreamonsky** [comment]
国内可能受网络影响，无法正常下载。可选择进群分流下载。 QQ群:980192646

**Comment by LilSpongeBob** [comment]
Thanks for adding a new mod

**Comment by Farhan160** [comment]
Why the mod vehicle the colour is pink?

**Comment by Farhan160** [comment]
The vehicle is pink

**Comment by CahyoKusum** [comment]
Why in my Game the vehicle is black?

**Comment by Mk48-a1** [comment]
Wheres m18 and m36 tanks destoryers?

**Comment by Doreamonsky** [comment]
![Android_Vehicle-T28-Prot](https://user-images.githubusercontent.com/12712112/71480744-ad0e6180-2835-11ea-8256-35e082322499.jpg)

T28-Prot has been added. [Click To View](https://github.com/Doreamonsky/Panzer-War-Mod-Storage/blob/master/ReadMe.md)

**Comment by FAJAgaming** [comment]
You should add
Pz Sfl IVc
Pz Sfl IVb
Marder II
Pz Kpfw II
AMX 50 Foch B

**Comment by Mk48-a1** [comment]
Wheres the T29 heavy tank mod from the ww2 middle 

And please bring back m18 hellcat amd m36 jackson TD from the ww2 middle

**Comment by Mk48-a1** [comment]
Wheres the T29 heavy tank from ww2middle file?

**Comment by paniquer** [comment]
Hello! Thanks for your game! Add please T95/FV4201 Chieftain for WW2late.
Jp.pz.e100 for WW2late
Stb-1 for WW2late
Thanks

**Comment by timurchik228** [comment]
> 国内可能受网络影响，无法正常下载。可选择进群分流下载。 QQ群:980192646

**Comment by timurchik228** [comment]
Where is wz111-5a and 121b?

**Comment by TzarOfMeh** [comment]
Pls add Bob Semple tank

**Comment by Mk48-a1** [comment]
Both e75 ts and T29 mod tanks are missing

**Comment by rubberducksmack** [comment]
Hey. With the Ferdinand Mod (sdkfz 184).
Is there going to be one for the Tiger P?
Also the jagdpanzer E100 (stug-E100) doesn't turn it's hull to aim the gun at a target that is out of its traverse arc.

**Comment by RusLan704** [comment]
Здравствуйте, можете добавить в игру таки Т 110 е 4, и Т 110 е 3, )

**Comment by Limon4ik287** [comment]
Please add t29 and tiger p to middle (пожалуйста добавьте т29 и тигр порше в мидл)

**Comment by trebuh05** [comment]
Please add t57 heavy, foch 155, Object 261, Object 268 v4, grille 15, AMX 50 b, t100 lt, t110e3, t110e4, Sheridan, AMX 13 105, panhard ebr 105, udes 15/16, stb-1, Object 430u.  
Thank you!

**Comment by Limon4ik287** [comment]
And add t26e4 super pershing to late

**Comment by Limon4ik287** [comment]
Когда обнова (when will the updated)

**Comment by nine9999nine9999** [comment]
About the ST-II,It's second gun cann't refill ammos when it running out of ammos and it hace only about 28 rounds before run out.Please make it's second gun have infinite ammos .

**Comment by Limon4ik287** [comment]
Oh and E50 ausf M to late

**Comment by MaxiiAlfaro** [comment]
Cómo descargo los mods de baidu? no entiendo cómo hacerlo

**Comment by ZoltisToth** [comment]
> Cómo descargo los mods de baidu? no entiendo cómo hacerlo

Write English please

**Comment by MaxiiAlfaro** [comment]
How do I download the baidu mods?  i don't understand how to do it

**Comment by kingtiger4599** [comment]
Very good work it's beautiful tanks you very much 😊😊

**Comment by Nikita589** [comment]
https://sketchfab.com/3d-models/t95fv4201-chieftain-9797d493ef9c42d28dfd3be88e98b1f0
T95/FV4201 chieftain

**Comment by kingtiger4599** [comment]
Tanks you very much for this mod i love it very good try

**Comment by HitriyLTvod** [comment]
Добавьте Об.261 please

**Comment by Limon4ik287** [comment]
And object268, m551 sheridan, object 261, t95/fv4201 chieftain. Thank you

**Comment by kingtiger4599** [comment]
We Can download this mod ??? Sorry i am french m'y english is bot perfect
Have a nice day😉

Le jeu. 19 mars 2020 à 12:28, Limon4ik287 <notifications@github.com> a
écrit :

**Comment by kingtiger4599** [comment]
when will mods be added to github to download them?
I wish you a good day


Le jeu. 19 mars 2020 à 12:59, Hugo Gallet <hugo.gallet255@gmail.com> a
écrit :

**Comment by Ehor220** [comment]
Можете добавить такие танки: XM 551 Sheridan ; Т95 ; EBR 90 (Извините если есть ошибки или что-то не дописал) ; ST Emil ; JagPanzer E100 (Для русских Яга Е 100 и так-же извините если есть ошибки и выше перечисленное) ; SPIC. Эти танки я очень хочу увидеть в игре!

**Comment by kingtiger4599** [comment]
you can count on me no problem for errors but in all cases panzer war
has become a better game with all the mods available thank you very
much

**Comment by trebuh05** [comment]
When new mods?

**Comment by trebuh05** [comment]
And please repair STRV 103b's suspension

**Comment by HitriyLTvod** [comment]
Добавьте Об.261 пожалуйста

**Comment by RuddyGamer** [comment]
I don't speak inglish and don't speak ruso I speak spanish 


Enviado desde mi Samsung Mobile de Telcel
-------- Mensaje original --------De: HitriyLTvod <notifications@github.com> Fecha: 25/3/20  11:41 AM  (GMT-06:00) A: Doreamonsky/Panzer-War-Lit-Mod <Panzer-War-Lit-Mod@noreply.github.com> CC: RuddyGamer <andysanchezvazquez@gmail.com>, Manual <manual@noreply.github.com> Asunto: Re: [Doreamonsky/Panzer-War-Lit-Mod] Mod Download / 模组下载一览 (#59) 


Добавьте Об.261 пожалуйста



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Doreamonsky/Panzer-War-Lit-Mod/issues/59#issuecomment-603984611",

"url": "https://github.com/Doreamonsky/Panzer-War-Lit-Mod/issues/59#issuecomment-603984611",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by timurchik228** [comment]
Шеридан есть ,но этот мод платный ,этот мод находиться в вк в группе panzer war ,cry of war,там есть пост с т22 ср ,он перекидывает в магазин модов ,где находится шеридан

**Comment by kingtiger4599** [comment]
Hello i don't have the payd version of panzer War


Le jeu. 26 mars 2020 à 08:47, timurchik228 <notifications@github.com> a
écrit :

**Comment by RuddyGamer** [comment]
no problem only you make the decision to buy the paid game or not

**Comment by MaxiiAlfaro** [comment]
is there a paid version?  Do you have mods that the free version doesn't have?  Google translator

**Comment by kingtiger4599** [comment]
I don't know so it's very sad because there a pad version

Le jeu. 26 mars 2020 à 11:23, MaxiiAlfaro <notifications@github.com> a
écrit :

**Comment by Limon4ik287** [comment]
Please new tanks

**Comment by ZoltisToth** [comment]
> Please new tanks

Do u want Jg.Pz.E100,or Obj.705 2?

**Comment by Cawa678** [comment]
> > Пожалуйста новые танки
> 
> Может ты хочешь Jg.Запретные зоны.E100, или Obj.705 2?

А что за об 705 2?

**Comment by kingtiger4599** [comment]
Hello when the New mod arrived

Le jeu. 26 mars 2020 à 11:53, Hugo Gallet <hugo.gallet255@gmail.com> a
écrit :

**Comment by RuddyGamer** [comment]
I don't know but I think you almost have a little patience

**Comment by ufxiyxoycohcohpucp** [comment]
Please add WWII Late mods to: Jg. pz E-100, chieftain mk 6, FV217 Badger, EBR-105, G. W E-100, ELC EVEN 90.
Pleeease pleas please!!

**Comment by ZoltisToth** [comment]
> Please add WWII Late mods to: Jg. pz E-100, chieftain mk 6, FV217 Badger, EBR-105, G. W E-100, ELC EVEN 90.
> Pleeease pleas please!!

I have Jg.Pz.E100, my VK is Zoltán Tóth, write me for him

**Comment by ufxiyxoycohcohpucp** [comment]
I'm sorry, but there are a lot of people with your name, and you are the
only one, I don’t know who to write, please drop the link to your page in
VK.

вс, 12 апр. 2020 г., 9:17 ZoltisToth <notifications@github.com>:

**Comment by ivanIRIJ** [comment]
Help me please how can i find the T29 tank mod file

**Comment by ivanIRIJ** [comment]
Please add M4A3E8 Fury please.

**Comment by ivanIRIJ** [comment]
And 17pdr SP Achilles
3D link: https://skfb.ly/IyQz

**Comment by ivanIRIJ** [comment]
I cannot get all android mods in baidu please help me guys

**Comment by ivanIRIJ** [comment]
Help me guys i cant download all tank files for android in baidu because the page is no longer available

**Comment by ivanIRIJ** [comment]
Please help

**Comment by ivanIRIJ** [comment]
😢😢

**Comment by RuddyGamer** [comment]
sorry but i don't understand the baidu page I can not help you

Enviado desde mi Samsung Mobile de Telcel
-------- Mensaje original --------De: ivanIRIJ <notifications@github.com> Fecha: 13/4/20  8:42 AM  (GMT-06:00) A: Doreamonsky/Panzer-War-Lit-Mod <Panzer-War-Lit-Mod@noreply.github.com> CC: RuddyGamer <andysanchezvazquez@gmail.com>, Manual <manual@noreply.github.com> Asunto: Re: [Doreamonsky/Panzer-War-Lit-Mod] Mod Download / 模组下载一览 (#59) 


😢😢



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Doreamonsky/Panzer-War-Lit-Mod/issues/59#issuecomment-612903670",

"url": "https://github.com/Doreamonsky/Panzer-War-Lit-Mod/issues/59#issuecomment-612903670",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by RuddyGamer** [comment]
Could you pass me the jgpanzer e100 please


Enviado desde mi Samsung Mobile de Telcel
-------- Mensaje original --------De: ZoltisToth <notifications@github.com> Fecha: 12/4/20  1:17 AM  (GMT-06:00) A: Doreamonsky/Panzer-War-Lit-Mod <Panzer-War-Lit-Mod@noreply.github.com> CC: RuddyGamer <andysanchezvazquez@gmail.com>, Manual <manual@noreply.github.com> Asunto: Re: [Doreamonsky/Panzer-War-Lit-Mod] Mod Download / 模组下载一览 (#59) 




Please add WWII Late mods to: Jg. pz E-100, chieftain mk 6, FV217 Badger, EBR-105, G. W E-100, ELC EVEN 90.


Pleeease pleas please!!



I have Jg.Pz.E100, my VK is Zoltán Tóth, write me for him



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Doreamonsky/Panzer-War-Lit-Mod/issues/59#issuecomment-612570204",

"url": "https://github.com/Doreamonsky/Panzer-War-Lit-Mod/issues/59#issuecomment-612570204",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ivanIRIJ** [comment]
It tells me that the baidu mods are permanently valid expired at 12-28-2019 13:09

**Comment by ivanIRIJ** [comment]
![Uploading IMG20200413212651.jpg…]()

**Comment by MaxiiAlfaro** [comment]
> Me dice que las modificaciones de Baidu son válidas de forma permanente y caducaron el 28/12/2019 13:09

https://m.vk.com/russianwindygroup  entra aquí

**Comment by ivanIRIJ** [comment]
Можете ли вы добавить этот танк
![uk-GB93_Caernarvon_AX](https://user-images.githubusercontent.com/61356661/79696138-5b3e8b00-82ad-11ea-9fa7-1a0c03b9c903.png)

**Comment by timurchik228** [comment]
Hi, I wrote this on the VK account, my nickname is Skril Slech

вс, 12 апр. 2020 г., 11:59 ufxiyxoycohcohpucp <notifications@github.com>:

**Comment by tacooooshxhs** [comment]
Add the sheridiaaan

**Comment by GottaNut** [comment]
What we need is Leopard 1 cause the the Leopard 1A5 in the game isn't the niceness looking tank cause the turret is put gar away from its original turret ring.

**Comment by GottaNut** [comment]
> Add the sheridian or JG PZ E100

These tanks are already mods expect the Sheridan but there is a T49 with a ATGM mod as well

**Comment by GottaNut** [comment]
Also can someone fis the st pz ll gun matlet  cause the gun has a lot more gun traverses.

**Comment by HitriyLTvod** [comment]
Ну добавьте об.261

**Comment by GottaNut** [comment]
> Ну добавьте об.261
That's a me tank we need like VT-1 or something actual good.

**Comment by Limon4ik287** [comment]
Fail to load is6 & fail to poad is2e. What to do?

**Comment by Cykablyatman123** [comment]
Pls fix the is6  and is2e

**Comment by Limon4ik287** [comment]
Plz add jagdpz e100 and t34e

**Comment by GottaNut** [comment]
Jagdpz e100 already added, and is6 and is2e isn't even a mod.
